{
    "cve": {
        "id": "CVE-2025-29606",
        "sourceIdentifier": "cve@mitre.org",
        "published": "2025-07-14T05:15:27.527",
        "lastModified": "2025-07-15T13:14:24.053",
        "vulnStatus": "Awaiting Analysis",
        "cveTags": [],
        "descriptions": [
            {
                "lang": "en",
                "value": "py-libp2p before 0.2.3 allows a peer to cause a denial of service (resource consumption) via a large RSA key."
            },
            {
                "lang": "es",
                "value": "py-libp2p anterior a 0.2.3 permite que un par provoque una denegaci\u00f3n de servicio (consumo de recursos) a trav\u00e9s de una clave RSA grande."
            }
        ],
        "metrics": {
            "cvssMetricV31": [
                {
                    "source": "cve@mitre.org",
                    "type": "Secondary",
                    "cvssData": {
                        "version": "3.1",
                        "vectorString": "CVSS:3.1\/AV:N\/AC:L\/PR:L\/UI:N\/S:U\/C:N\/I:N\/A:L",
                        "baseScore": 4.3,
                        "baseSeverity": "MEDIUM",
                        "attackVector": "NETWORK",
                        "attackComplexity": "LOW",
                        "privilegesRequired": "LOW",
                        "userInteraction": "NONE",
                        "scope": "UNCHANGED",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "availabilityImpact": "LOW"
                    },
                    "exploitabilityScore": 2.8,
                    "impactScore": 1.4
                }
            ]
        },
        "weaknesses": [
            {
                "source": "cve@mitre.org",
                "type": "Primary",
                "description": [
                    {
                        "lang": "en",
                        "value": "CWE-770"
                    }
                ]
            }
        ],
        "references": [
            {
                "url": "https:\/\/github.com\/libp2p\/py-libp2p\/compare\/v0.2.2...v0.2.3",
                "source": "cve@mitre.org"
            },
            {
                "url": "https:\/\/github.com\/libp2p\/py-libp2p\/issues\/526",
                "source": "cve@mitre.org"
            },
            {
                "url": "https:\/\/github.com\/libp2p\/py-libp2p\/pull\/531\/files",
                "source": "cve@mitre.org"
            }
        ]
    }
}